import { getSession } from "next-auth/react";
import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Login from "../components/Login";
import RightSidebar from "../components/RightSidebar";
import Siderbar from "../components/Siderbar";

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="flex bg-gray-100 mt-2">
        {/* Left Sidebar */}
        <Siderbar />

        {/* Feed (Create Post and Posts) */}
        <Feed />

        {/* Right Sidebar */}
        <RightSidebar />
      </main>
    </div>
  );
}

// ServerSide Rendering
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
